// backend/src/utils/catchAsync.js
module.exports = fn => {
  return (req, res, next) => {
    fn(req, res, next).catch(next); // Catch any errors and pass to next (error handling middleware)
  };
};